[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F401CCUx"
rustflags = [
    "-C",
    "link-arg=-Tlink.x",

    "-C",
    "link-arg=--nmagic",

    # See https://defmt.ferrous-systems.com/setup
    "-C",
    "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
CHIPSERIE = "stm32f401"
