on:
  push:
  pull_request:
  workflow_dispatch:

name: CI
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # see https://devenv.sh/integrations/github-actions/
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - run: cargo check
        shell: devenv shell bash -- -e {0}
        working-directory: ./firmware

      - run: cargo clippy -- -W clippy::pedantic
        shell: devenv shell bash -- -e {0}
        working-directory: ./firmware

      - run: cargo fmt --all -- --check
        shell: devenv shell bash -- -e {0}
        working-directory: ./firmware

      - run: cargo test
        shell: devenv shell bash -- -e {0}
        working-directory: ./firmware

      - run: cargo build --release
        shell: devenv shell bash -- -e {0}
        working-directory: ./firmware
