name: Sync README.md

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/sync-readme.yml
      - .github/workflows/sync-readme.yml # this file
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.POMP_GH_PAT }}
          CONFIG_PATH: .github/sync-readme.yml
          ASSIGNEES: pompydev
